package com.lin.entities;
// Generated Dec 11, 2012 9:16:27 PM by Hibernate Tools 3.2.1.GA



/**
 * AdvanceRule generated by hbm2java
 */
public class AdvanceRule  implements java.io.Serializable {


     private int id;
     private int facilityTypeId;
     private int minDays;
     private int maxDays;

    public AdvanceRule() {
    }

    public AdvanceRule(int id, int facilityTypeId, int minDays, int maxDays) {
       this.id = id;
       this.facilityTypeId = facilityTypeId;
       this.minDays = minDays;
       this.maxDays = maxDays;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFacilityTypeId() {
        return this.facilityTypeId;
    }
    
    public void setFacilityTypeId(int facilityTypeId) {
        this.facilityTypeId = facilityTypeId;
    }
    public int getMinDays() {
        return this.minDays;
    }
    
    public void setMinDays(int minDays) {
        this.minDays = minDays;
    }
    public int getMaxDays() {
        return this.maxDays;
    }
    
    public void setMaxDays(int maxDays) {
        this.maxDays = maxDays;
    }




}


