package com.lin.entities;
// Generated Dec 12, 2012 6:43:41 PM by Hibernate Tools 3.2.1.GA



/**
 * AdvanceRule generated by hbm2java
 */
public class AdvanceRule  implements java.io.Serializable {


     private int id;
     private FacilityType facilityType;
     private int minDays;
     private int maxDays;

    public AdvanceRule() {
    }

    public AdvanceRule(int id, FacilityType facilityType, int minDays, int maxDays) {
       this.id = id;
       this.facilityType = facilityType;
       this.minDays = minDays;
       this.maxDays = maxDays;
    }
    
    public AdvanceRule(FacilityType facilityType, int minDays, int maxDays) {
       this.facilityType = facilityType;
       this.minDays = minDays;
       this.maxDays = maxDays;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public int getMinDays() {
        return this.minDays;
    }
    
    public void setMinDays(int minDays) {
        this.minDays = minDays;
    }
    public int getMaxDays() {
        return this.maxDays;
    }
    
    public void setMaxDays(int maxDays) {
        this.maxDays = maxDays;
    }

    @Override
    public String toString() {
        return "AdvanceRule{" + "minDays=" + minDays + ", maxDays=" + maxDays + '}';
    }

    


}


