package com.lin.entities;
// Generated Jan 21, 2013 5:22:33 PM by Hibernate Tools 3.2.1.GA



/**
 * Amenity generated by hbm2java
 */
public class Amenity  implements java.io.Serializable {


     private Integer id;
     private AmenityCategory amenityCategory;
     private String name;
     private String description;
     private int postalCode;
     private String contactNo;
     private int lat;
     private int lng;
     private String unitNo;
     private String streetName;

    public Amenity() {
    }

	
    public Amenity(AmenityCategory amenityCategory, String name, int postalCode, int lat, int lng) {
        this.amenityCategory = amenityCategory;
        this.name = name;
        this.postalCode = postalCode;
        this.lat = lat;
        this.lng = lng;
    }
    public Amenity(AmenityCategory amenityCategory, String name, String description, int postalCode, String contactNo, int lat, int lng, String unitNo, String streetName) {
       this.amenityCategory = amenityCategory;
       this.name = name;
       this.description = description;
       this.postalCode = postalCode;
       this.contactNo = contactNo;
       this.lat = lat;
       this.lng = lng;
       this.unitNo = unitNo;
       this.streetName = streetName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AmenityCategory getAmenityCategory() {
        return this.amenityCategory;
    }
    
    public void setAmenityCategory(AmenityCategory amenityCategory) {
        this.amenityCategory = amenityCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(int postalCode) {
        this.postalCode = postalCode;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public int getLat() {
        return this.lat;
    }
    
    public void setLat(int lat) {
        this.lat = lat;
    }
    public int getLng() {
        return this.lng;
    }
    
    public void setLng(int lng) {
        this.lng = lng;
    }
    public String getUnitNo() {
        return this.unitNo;
    }
    
    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }




}


