package com.lin.entities;
// Generated Jan 20, 2013 6:53:45 PM by Hibernate Tools 3.2.1.GA



/**
 * Amenity generated by hbm2java
 */
public class Amenity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String address;
     private int postalCode;
     private String contactNo;
     private int lat;
     private int lng;
     private String category;

    public Amenity() {
    }

	
    public Amenity(String name, String address, int postalCode, int lat, int lng, String category) {
        this.name = name;
        this.address = address;
        this.postalCode = postalCode;
        this.lat = lat;
        this.lng = lng;
        this.category = category;
    }
    public Amenity(String name, String description, String address, int postalCode, String contactNo, int lat, int lng, String category) {
       this.name = name;
       this.description = description;
       this.address = address;
       this.postalCode = postalCode;
       this.contactNo = contactNo;
       this.lat = lat;
       this.lng = lng;
       this.category = category;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(int postalCode) {
        this.postalCode = postalCode;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public int getLat() {
        return this.lat;
    }
    
    public void setLat(int lat) {
        this.lat = lat;
    }
    public int getLng() {
        return this.lng;
    }
    
    public void setLng(int lng) {
        this.lng = lng;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


