package com.lin.entities;
// Generated Jan 20, 2013 6:53:45 PM by Hibernate Tools 3.2.1.GA

import org.apache.commons.lang3.StringEscapeUtils;




/**
 * AmenityCategory generated by hbm2java
 */
public class AmenityCategory  implements java.io.Serializable {


     private Integer id;
     private String name;

    public AmenityCategory() {
    }

    public AmenityCategory(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return StringEscapeUtils.escapeEcmaScript(name);
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


