package com.lin.entities;
// Generated Dec 12, 2012 6:43:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CloseRule generated by hbm2java
 */
public class CloseRule  implements java.io.Serializable {


     private int id;
     private FacilityType facilityType;
     private Date startDate;
     private Date endDate;

    public CloseRule() {
    }

    public CloseRule(int id, FacilityType facilityType, Date startDate, Date endDate) {
       this.id = id;
       this.facilityType = facilityType;
       this.startDate = startDate;
       this.endDate = endDate;
    }
    
    public CloseRule(FacilityType facilityType, Date startDate, Date endDate) {
       this.facilityType = facilityType;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


