package com.lin.entities;
// Generated Dec 24, 2012 5:54:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CloseRule generated by hbm2java
 */
public class CloseRule  implements java.io.Serializable {


     private Integer id;
     private FacilityType facilityType;
     private Date startDate;
     private Date endDate;
     private boolean repeatedAnnually;

    public CloseRule() {
    }

    public CloseRule(FacilityType facilityType, Date startDate, Date endDate, boolean repeatedAnnually) {
       this.facilityType = facilityType;
       this.startDate = startDate;
       this.endDate = endDate;
       this.repeatedAnnually = repeatedAnnually;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public boolean isRepeatedAnnually() {
        return this.repeatedAnnually;
    }
    
    public void setRepeatedAnnually(boolean repeatedAnnually) {
        this.repeatedAnnually = repeatedAnnually;
    }




}


