package com.lin.entities;
// Generated Feb 7, 2013 9:01:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int commentId;
     private User user;
     private Post post;
     private String text;
     private Date commentDate;

    public Comment() {
    }

	
    public Comment(int commentId, User user, Post post) {
        this.commentId = commentId;
        this.user = user;
        this.post = post;
    }
    public Comment(int commentId, User user, Post post, String text, Date commentDate) {
       this.commentId = commentId;
       this.user = user;
       this.post = post;
       this.text = text;
       this.commentDate = commentDate;
    }
   
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getCommentDate() {
        return this.commentDate;
    }
    
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }




}


