package com.lin.entities;
// Generated Mar 29, 2013 12:50:57 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Enquiry generated by hbm2java
 */
public class Enquiry  implements java.io.Serializable {


     private int id;
     private int userId;
     private boolean status;
     private Date opened;
     private Date lastUpdated;
     private String regarding;
     private String text;
     private Integer replyId;

    public Enquiry() {
    }

	
    public Enquiry(int id, int userId, boolean status, Date opened, Date lastUpdated, String regarding, String text) {
        this.id = id;
        this.userId = userId;
        this.status = status;
        this.opened = opened;
        this.lastUpdated = lastUpdated;
        this.regarding = regarding;
        this.text = text;
    }
    public Enquiry(int id, int userId, boolean status, Date opened, Date lastUpdated, String regarding, String text, Integer replyId) {
       this.id = id;
       this.userId = userId;
       this.status = status;
       this.opened = opened;
       this.lastUpdated = lastUpdated;
       this.regarding = regarding;
       this.text = text;
       this.replyId = replyId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Date getOpened() {
        return this.opened;
    }
    
    public void setOpened(Date opened) {
        this.opened = opened;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public String getRegarding() {
        return this.regarding;
    }
    
    public void setRegarding(String regarding) {
        this.regarding = regarding;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getReplyId() {
        return this.replyId;
    }
    
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }




}


