package com.lin.entities;
// Generated Jan 27, 2013 3:26:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Enquiry generated by hbm2java
 */
public class Enquiry  implements java.io.Serializable {


     private int id;
     private User user;
     private Date enquiryTimeStamp;
     private String title;
     private String text;
     private boolean isResolved;

    public Enquiry() {
    }

    public Enquiry(int id, User user, Date enquiryTimeStamp, String title, String text, boolean isResolved) {
       this.id = id;
       this.user = user;
       this.enquiryTimeStamp = enquiryTimeStamp;
       this.title = title;
       this.text = text;
       this.isResolved = isResolved;
    }
    public Enquiry(User user, String title, String text, boolean isResolved) {
       //this.id = id;
       this.user = user;
       //this.enquiryTimeStamp = enquiryTimeStamp;
       this.title = title;
       this.text = text;
       this.isResolved = isResolved;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getEnquiryTimeStamp() {
        return this.enquiryTimeStamp;
    }
    
    public void setEnquiryTimeStamp(Date enquiryTimeStamp) {
        this.enquiryTimeStamp = enquiryTimeStamp;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public boolean isIsResolved() {
        return this.isResolved;
    }
    
    public void setIsResolved(boolean isResolved) {
        this.isResolved = isResolved;
    }




}


