package com.lin.entities;
// Generated Mar 29, 2013 1:06:19 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enquiry generated by hbm2java
 */
public class Enquiry  implements java.io.Serializable {


     private int id;
     private User user;
     private Enquiry enquiry;
     private boolean status;
     private Date opened;
     private Date lastUpdated;
     private String regarding;
     private String text;
     private Set enquiries = new HashSet(0);

    public Enquiry() {
    }

	
    public Enquiry(int id, User user, boolean status, Date opened, Date lastUpdated, String regarding, String text) {
        this.id = id;
        this.user = user;
        this.status = status;
        this.opened = opened;
        this.lastUpdated = lastUpdated;
        this.regarding = regarding;
        this.text = text;
    }
    public Enquiry(int id, User user, Enquiry enquiry, boolean status, Date opened, Date lastUpdated, String regarding, String text, Set enquiries) {
       this.id = id;
       this.user = user;
       this.enquiry = enquiry;
       this.status = status;
       this.opened = opened;
       this.lastUpdated = lastUpdated;
       this.regarding = regarding;
       this.text = text;
       this.enquiries = enquiries;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Enquiry getEnquiry() {
        return this.enquiry;
    }
    
    public void setEnquiry(Enquiry enquiry) {
        this.enquiry = enquiry;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Date getOpened() {
        return this.opened;
    }
    
    public void setOpened(Date opened) {
        this.opened = opened;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public String getRegarding() {
        return this.regarding;
    }
    
    public void setRegarding(String regarding) {
        this.regarding = regarding;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Set getEnquiries() {
        return this.enquiries;
    }
    
    public void setEnquiries(Set enquiries) {
        this.enquiries = enquiries;
    }




}


