package com.lin.entities;
// Generated Feb 22, 2013 4:39:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EventInvite generated by hbm2java
 */
public class EventInvite  implements java.io.Serializable {

    public void setInviteStatus(Type type) {
        this.inviteStatus = getTypeStringFromEnum(type);
    }

    public enum Type{
        ACCEPTED,REJECTED,PENDING
    }

     private Integer id;
     private Date timestamp;
     private Event event;
     private User user;
     private String inviteStatus;

    public EventInvite() {
    }

    public EventInvite(Event event, User user, String inviteStatus) {
       this.event = event;
       this.user = user;
       this.inviteStatus = inviteStatus;
    }
    
    //Use this for creating events
   public EventInvite(Event event, User user, EventInvite.Type type) {
       this.event = event;
       this.user = user;
       this.inviteStatus = getTypeStringFromEnum(type);
    }
   
   public String getTypeStringFromEnum(EventInvite.Type t){
       if(t == EventInvite.Type.ACCEPTED){
           return "ACCEPTED";
       }else if(t == EventInvite.Type.REJECTED){
           return "REJECTED";
       }else if(t == EventInvite.Type.PENDING){
           return "PENDING";
       }
       return "";
   }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getInviteStatus() {
        return this.inviteStatus;
    }
    
    public void setInviteStatus(String inviteStatus) {
        this.inviteStatus = inviteStatus;
    }




}


