package com.lin.entities;
// Generated Feb 22, 2013 4:39:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EventInappropriate generated by hbm2java
 */
public class EventInappropriate  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private Event event;
     private User user;

    public EventInappropriate() {
    }

    public EventInappropriate(Event event, User user) {
       this.event = event;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


