package com.lin.entities;
// Generated Dec 29, 2012 4:08:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Facility generated by hbm2java
 */
public class Facility  implements java.io.Serializable {


     private Integer id;
     private FacilityType facilityType;
     private String name;
     private int facilityLng;
     private int facilityLat;
     private Set bookings = new HashSet(0);

    public Facility() {
    }

	
    public Facility(FacilityType facilityType, String name, int facilityLng, int facilityLat) {
        this.facilityType = facilityType;
        this.name = name;
        this.facilityLng = facilityLng;
        this.facilityLat = facilityLat;
    }
    public Facility(FacilityType facilityType, String name, int facilityLng, int facilityLat, Set bookings) {
       this.facilityType = facilityType;
       this.name = name;
       this.facilityLng = facilityLng;
       this.facilityLat = facilityLat;
       this.bookings = bookings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getFacilityLng() {
        return this.facilityLng;
    }
    
    public void setFacilityLng(int facilityLng) {
        this.facilityLng = facilityLng;
    }
    public int getFacilityLat() {
        return this.facilityLat;
    }
    
    public void setFacilityLat(int facilityLat) {
        this.facilityLat = facilityLat;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


