package com.lin.entities;
// Generated Dec 12, 2012 6:43:41 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * FacilityType generated by hbm2java
 */
public class FacilityType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     @OnDelete(action = OnDeleteAction.CASCADE)
     private Set limitRules = new HashSet(0);
     @OnDelete(action = OnDeleteAction.CASCADE)
     private Set advanceRules = new HashSet(0);
     @OnDelete(action = OnDeleteAction.CASCADE)
     private Set facilities = new HashSet(0);
     @OnDelete(action = OnDeleteAction.CASCADE)
     private Set openRules = new HashSet(0);
     @OnDelete(action = OnDeleteAction.CASCADE)
     private Set closeRules = new HashSet(0);
     

    public FacilityType() {
    }

	
    public FacilityType(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public FacilityType(String name, String description, Set limitRules, Set advanceRules, Set facilities, Set openRules, Set closeRules) {
       this.name = name;
       this.description = description;
       this.limitRules = limitRules;
       this.advanceRules = advanceRules;
       this.facilities = facilities;
       this.openRules = openRules;
       this.closeRules = closeRules;
    }
    
     public FacilityType(String name, String description, Set limitRules, Set advanceRules, Set openRules, Set closeRules) {
       this.name = name;
       this.description = description;
       this.limitRules = limitRules;
       this.advanceRules = advanceRules;
       this.openRules = openRules;
       this.closeRules = closeRules;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getLimitRules() {
        return this.limitRules;
    }
    
    public void setLimitRules(Set limitRules) {
        this.limitRules = limitRules;
    }
    public Set getAdvanceRules() {
        return this.advanceRules;
    }
    
    public void setAdvanceRules(Set advanceRules) {
        this.advanceRules = advanceRules;
    }
    public Set getFacilities() {
        return this.facilities;
    }
    
    public void setFacilities(Set facilities) {
        this.facilities = facilities;
    }
    public Set getOpenRules() {
        return this.openRules;
    }
    
    public void setOpenRules(Set openRules) {
        this.openRules = openRules;
    }
    public Set getCloseRules() {
        return this.closeRules;
    }
    
    public void setCloseRules(Set closeRules) {
        this.closeRules = closeRules;
    }




}


