package com.lin.entities;
// Generated Feb 2, 2013 9:48:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Friendship generated by hbm2java
 */
public class Friendship  implements java.io.Serializable {


     private int id;
     private User userByUserIdTwo;
     private User userByUserIdOne;
     private Date date;
     private String relationshipOneTwo;
     private String relationshipTwoOne;

    public Friendship() {
    }

    public Friendship(int id, User userByUserIdTwo, User userByUserIdOne, Date date, String relationshipOneTwo, String relationshipTwoOne) {
       this.id = id;
       this.userByUserIdTwo = userByUserIdTwo;
       this.userByUserIdOne = userByUserIdOne;
       this.date = date;
       this.relationshipOneTwo = relationshipOneTwo;
       this.relationshipTwoOne = relationshipTwoOne;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUserByUserIdTwo() {
        return this.userByUserIdTwo;
    }
    
    public void setUserByUserIdTwo(User userByUserIdTwo) {
        this.userByUserIdTwo = userByUserIdTwo;
    }
    public User getUserByUserIdOne() {
        return this.userByUserIdOne;
    }
    
    public void setUserByUserIdOne(User userByUserIdOne) {
        this.userByUserIdOne = userByUserIdOne;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getRelationshipOneTwo() {
        return this.relationshipOneTwo;
    }
    
    public void setRelationshipOneTwo(String relationshipOneTwo) {
        this.relationshipOneTwo = relationshipOneTwo;
    }
    public String getRelationshipTwoOne() {
        return this.relationshipTwoOne;
    }
    
    public void setRelationshipTwoOne(String relationshipTwoOne) {
        this.relationshipTwoOne = relationshipTwoOne;
    }




}


