package com.lin.entities;
// Generated Feb 25, 2013 2:38:19 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Friendship generated by hbm2java
 */
public class Friendship  implements java.io.Serializable {


     private Integer id;
     private User userByUserIdTwo;
     private User userByUserIdOne;
     private Date date;
     private String relationshipOneTwo;
     private String relationshipTwoOne;
     private boolean hasAccepted;

    public Friendship() {
    }

    public Friendship(User userByUserIdTwo, User userByUserIdOne, Date date, String relationshipOneTwo, String relationshipTwoOne, boolean hasAccepted) {
       this.userByUserIdTwo = userByUserIdTwo;
       this.userByUserIdOne = userByUserIdOne;
       this.date = date;
       this.relationshipOneTwo = relationshipOneTwo;
       this.relationshipTwoOne = relationshipTwoOne;
       this.hasAccepted = hasAccepted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByUserIdTwo() {
        return this.userByUserIdTwo;
    }
    
    public void setUserByUserIdTwo(User userByUserIdTwo) {
        this.userByUserIdTwo = userByUserIdTwo;
    }
    public User getUserByUserIdOne() {
        return this.userByUserIdOne;
    }
    
    public void setUserByUserIdOne(User userByUserIdOne) {
        this.userByUserIdOne = userByUserIdOne;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getRelationshipOneTwo() {
        return this.relationshipOneTwo;
    }
    
    public void setRelationshipOneTwo(String relationshipOneTwo) {
        this.relationshipOneTwo = relationshipOneTwo;
    }
    public String getRelationshipTwoOne() {
        return this.relationshipTwoOne;
    }
    
    public void setRelationshipTwoOne(String relationshipTwoOne) {
        this.relationshipTwoOne = relationshipTwoOne;
    }
    public boolean isHasAccepted() {
        return this.hasAccepted;
    }
    
    public void setHasAccepted(boolean hasAccepted) {
        this.hasAccepted = hasAccepted;
    }




}


