package com.lin.entities;
// Generated Dec 12, 2012 6:43:41 PM by Hibernate Tools 3.2.1.GA



/**
 * LimitRule generated by hbm2java
 */
public class LimitRule  implements java.io.Serializable {


     private int id;
     private FacilityType facilityType;
     private int sessions;
     private int numberOfTimeframe;
     private String timeframeType;

    public LimitRule() {
    }

    public LimitRule(int id, FacilityType facilityType, int sessions, int numberOfTimeframe, String timeframeType) {
       this.id = id;
       this.facilityType = facilityType;
       this.sessions = sessions;
       this.numberOfTimeframe = numberOfTimeframe;
       this.timeframeType = timeframeType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public int getSessions() {
        return this.sessions;
    }
    
    public void setSessions(int sessions) {
        this.sessions = sessions;
    }
    public int getNumberOfTimeframe() {
        return this.numberOfTimeframe;
    }
    
    public void setNumberOfTimeframe(int numberOfTimeframe) {
        this.numberOfTimeframe = numberOfTimeframe;
    }
    public String getTimeframeType() {
        return this.timeframeType;
    }
    
    public void setTimeframeType(String timeframeType) {
        this.timeframeType = timeframeType;
    }




}


