package com.lin.entities;
// Generated Dec 11, 2012 9:16:27 PM by Hibernate Tools 3.2.1.GA



/**
 * LimitRule generated by hbm2java
 */
public class LimitRule  implements java.io.Serializable {


     private int id;
     private int facilityTypeId;
     private int sessions;
     private String timeframe;

    public LimitRule() {
    }

    public LimitRule(int id, int facilityTypeId, int sessions, String timeframe) {
       this.id = id;
       this.facilityTypeId = facilityTypeId;
       this.sessions = sessions;
       this.timeframe = timeframe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFacilityTypeId() {
        return this.facilityTypeId;
    }
    
    public void setFacilityTypeId(int facilityTypeId) {
        this.facilityTypeId = facilityTypeId;
    }
    public int getSessions() {
        return this.sessions;
    }
    
    public void setSessions(int sessions) {
        this.sessions = sessions;
    }
    public String getTimeframe() {
        return this.timeframe;
    }
    
    public void setTimeframe(String timeframe) {
        this.timeframe = timeframe;
    }




}


