package com.lin.entities;
// Generated Feb 22, 2013 4:39:59 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private Event event;
     private User userBySenderId;
     private Post post;
     private User userByReceiverId;
     private String type;

    public Notification() {
    }

	
    public Notification(User userBySenderId, User userByReceiverId, String type) {
        this.userBySenderId = userBySenderId;
        this.userByReceiverId = userByReceiverId;
        this.type = type;
    }
    public Notification(Event event, User userBySenderId, Post post, User userByReceiverId, String type) {
       this.event = event;
       this.userBySenderId = userBySenderId;
       this.post = post;
       this.userByReceiverId = userByReceiverId;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUserBySenderId() {
        return this.userBySenderId;
    }
    
    public void setUserBySenderId(User userBySenderId) {
        this.userBySenderId = userBySenderId;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUserByReceiverId() {
        return this.userByReceiverId;
    }
    
    public void setUserByReceiverId(User userByReceiverId) {
        this.userByReceiverId = userByReceiverId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


