package com.lin.entities;
// Generated Dec 25, 2012 4:22:58 AM by Hibernate Tools 3.2.1.GA


import com.lin.entities.FacilityType;
import java.util.Date;

/**
 * OpenRule generated by hbm2java
 */
public class OpenRule  implements java.io.Serializable {


     private Integer id;
     private FacilityType facilityType;
     private Date startTime;
     private Date endTime;

    public OpenRule() {
    }

    public OpenRule(FacilityType facilityType, Date startTime, Date endTime) {
       this.facilityType = facilityType;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FacilityType getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(FacilityType facilityType) {
        this.facilityType = facilityType;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


