package com.lin.entities;
// Generated Dec 11, 2012 9:16:27 PM by Hibernate Tools 3.2.1.GA



/**
 * OpenRule generated by hbm2java
 */
public class OpenRule  implements java.io.Serializable {


     private int id;
     private int facilityTypeId;
     private String dayOfWeek;
     private int startTime;
     private int endTime;

    public OpenRule() {
    }

    public OpenRule(int id, int facilityTypeId, String dayOfWeek, int startTime, int endTime) {
       this.id = id;
       this.facilityTypeId = facilityTypeId;
       this.dayOfWeek = dayOfWeek;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFacilityTypeId() {
        return this.facilityTypeId;
    }
    
    public void setFacilityTypeId(int facilityTypeId) {
        this.facilityTypeId = facilityTypeId;
    }
    public String getDayOfWeek() {
        return this.dayOfWeek;
    }
    
    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }
    public int getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(int startTime) {
        this.startTime = startTime;
    }
    public int getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(int endTime) {
        this.endTime = endTime;
    }




}


