package com.lin.entities;
// Generated Jan 28, 2013 1:35:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private int postId;
     private Post post;
     private User user;
     private String message;
     private Date date;
     private Integer noOfLikes;
     private Set posts = new HashSet(0);

    public Post() {
    }

	
    public Post(int postId, User user) {
        this.postId = postId;
        this.user = user;
    }
    
    
    public Post(int postId, Post post, User user, String message, Date date, Integer noOfLikes, Set posts) {
       this.postId = postId;
       this.post = post;
       this.user = user;
       this.message = message;
       this.date = date;
       this.noOfLikes = noOfLikes;
       this.posts = posts;
    }
   
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getNoOfLikes() {
        return this.noOfLikes;
    }
    
    public void setNoOfLikes(Integer noOfLikes) {
        this.noOfLikes = noOfLikes;
    }
    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }




}


