package com.lin.entities;
// Generated Jan 16, 2013 4:23:59 PM by Hibernate Tools 3.2.1.GA



/**
 * ResourceCategory generated by hbm2java
 */
public class ResourceCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;

    public ResourceCategory() {
    }

    public ResourceCategory(String name, String description) {
       this.name = name;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


