package com.lin.entities;
// Generated Jan 14, 2013 5:42:36 PM by Hibernate Tools 3.2.1.GA



/**
 * ResourceCategories generated by hbm2java
 */
public class ResourceCategories  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String decription;

    public ResourceCategories() {
    }

    public ResourceCategories(String name, String decription) {
       this.name = name;
       this.decription = decription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDecription() {
        return this.decription;
    }
    
    public void setDecription(String decription) {
        this.decription = decription;
    }




}


