package com.lin.entities;
// Generated Dec 12, 2012 6:30:41 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set userTemps = new HashSet(0);
     private Set users = new HashSet(0);

    public Role() {
    }

	
    public Role(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Role(String name, String description, Set userTemps, Set users) {
       this.name = name;
       this.description = description;
       this.userTemps = userTemps;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUserTemps() {
        return this.userTemps;
    }
    
    public void setUserTemps(Set userTemps) {
        this.userTemps = userTemps;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


