package com.lin.entities;
// Generated Oct 24, 2012 12:17:41 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<UserTemp> userTemps = new HashSet<UserTemp>(0);
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Role(String name, String description, Set<UserTemp> userTemps, Set<User> users) {
       this.name = name;
       this.description = description;
       this.userTemps = userTemps;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<UserTemp> getUserTemps() {
        return this.userTemps;
    }
    
    public void setUserTemps(Set<UserTemp> userTemps) {
        this.userTemps = userTemps;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


