package com.lin.entities;
// Generated Jan 18, 2013 4:37:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SubmittedForm generated by hbm2java
 */
public class SubmittedForm  implements java.io.Serializable {


     private Integer id;
     private String user;
     private Date timeSubmitted;
     private String fileName;
     private boolean processed;

    public SubmittedForm() {
    }

    public SubmittedForm(String user, Date timeSubmitted, String fileName, boolean processed) {
       this.user = user;
       this.timeSubmitted = timeSubmitted;
       this.fileName = fileName;
       this.processed = processed;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Date getTimeSubmitted() {
        return this.timeSubmitted;
    }
    
    public void setTimeSubmitted(Date timeSubmitted) {
        this.timeSubmitted = timeSubmitted;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public boolean isProcessed() {
        return this.processed;
    }
    
    public void setProcessed(boolean processed) {
        this.processed = processed;
    }




}


