package com.lin.entities;
// Generated Jan 28, 2013 3:05:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserTemp generated by hbm2java
 */
public class UserTemp  implements java.io.Serializable {


     private Integer userId;
     private Role role;
     private Block block;
     private String password;
     private String userName;
     private String firstname;
     private String lastname;
     private Date dob;
     private Integer level;
     private Integer unit;
     private String facebookId;
     private String mobileNo;
     private String email;
     private Date birthday;
     private String studiedAt;
     private String worksAt;
     private String aboutMe;

    public UserTemp() {
    }

	
    public UserTemp(Role role, String password, String userName, String firstname, String lastname) {
        this.role = role;
        this.password = password;
        this.userName = userName;
        this.firstname = firstname;
        this.lastname = lastname;
    }
    
    public UserTemp(Role role, Block block, String password, String userName,
            String firstname, String lastname, Date dob, String mobileNo,
            String email, Integer level, Integer unit) {
        this.role = role;
        this.block = block;
        this.password = password;
        this.userName = userName;
        this.firstname = firstname;
        this.lastname = lastname;
        this.dob = dob;
        this.mobileNo = mobileNo;
        this.email = email;
        this.level = level;
        this.unit = unit;
    }
    
    public UserTemp(Role role, Block block, String password, String userName, String firstname, String lastname, Date dob, Integer level, Integer unit, String facebookId, String mobileNo, String email, Date birthday, String studiedAt, String worksAt, String aboutMe) {
       this.role = role;
       this.block = block;
       this.password = password;
       this.userName = userName;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dob = dob;
       this.level = level;
       this.unit = unit;
       this.facebookId = facebookId;
       this.mobileNo = mobileNo;
       this.email = email;
       this.birthday = birthday;
       this.studiedAt = studiedAt;
       this.worksAt = worksAt;
       this.aboutMe = aboutMe;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public Block getBlock() {
        return this.block;
    }
    
    public void setBlock(Block block) {
        this.block = block;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
    public Integer getUnit() {
        return this.unit;
    }
    
    public void setUnit(Integer unit) {
        this.unit = unit;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getStudiedAt() {
        return this.studiedAt;
    }
    
    public void setStudiedAt(String studiedAt) {
        this.studiedAt = studiedAt;
    }
    public String getWorksAt() {
        return this.worksAt;
    }
    
    public void setWorksAt(String worksAt) {
        this.worksAt = worksAt;
    }
    public String getAboutMe() {
        return this.aboutMe;
    }
    
    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }




}


