package com.lin.entities;
// Generated Oct 24, 2012 12:17:41 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Role role;
     private Block block;
     private String password;
     private String userName;
     private String firstname;
     private String lastname;
     private Date dob;
     private Integer level;
     private Integer unit;
     private String facebookId;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public User() {
    }

	
    public User(Role role, String password, String userName, String firstname, String lastname, Date dob) {
        this.role = role;
        this.password = password;
        this.userName = userName;
        this.firstname = firstname;
        this.lastname = lastname;
        this.dob = dob;
    }
    public User(Role role, Block block, String password, String userName, String firstname, String lastname, Date dob, Integer level, Integer unit) {
       this.role = role;
       this.block = block;
       this.password = password;
       this.userName = userName;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dob = dob;
       this.level = level;
       this.unit = unit;
    }
    public User(int userId, Role role, Block block,  String userName, String firstname, String lastname,  Integer level, Integer unit) {
       this.userId = userId;
       this.role = role;
       this.block = block;
       this.userName = userName;
       this.firstname = firstname;
       this.lastname = lastname;
       this.level = level;
       this.unit = unit;
    }
    public User(Role role, Block block, String password, String userName, String firstname, String lastname, Date dob, Integer level, Integer unit, String facebookId) {
       this.role = role;
       this.block = block;
       this.password = password;
       this.userName = userName;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dob = dob;
       this.level = level;
       this.unit = unit;
       this.facebookId = facebookId;
    }
    public User(Role role, Block block, String password, String userName, String firstname, String lastname, Date dob, Integer level, Integer unit, String facebookId, Set<Booking> bookings) {
       this.role = role;
       this.block = block;
       this.password = password;
       this.userName = userName;
       this.firstname = firstname;
       this.lastname = lastname;
       this.dob = dob;
       this.level = level;
       this.unit = unit;
       this.facebookId = facebookId;
       this.bookings = bookings;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public Block getBlock() {
        return this.block;
    }
    
    public void setBlock(Block block) {
        this.block = block;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }
    public Integer getUnit() {
        return this.unit;
    }
    
    public void setUnit(Integer unit) {
        this.unit = unit;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


